export interface AIServiceResponse {
  success: boolean;
  content?: string;
  error?: string;
  model?: string; // AI模型信息
}

export class AIService {
  private static readonly GEMINI_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';
  private static readonly OPENROUTER_URL = 'https://openrouter.ai/api/v1/chat/completions';

  static async generateResume(prompt: string, selectedModel?: string): Promise<AIServiceResponse> {
    const aiService = selectedModel || process.env.AI_SERVICE || 'gemini';
    
    try {
      if (aiService === 'gemini') {
        return await this.callGemini(prompt);
      } else if (aiService === 'deepseek') {
        return await this.callDeepSeek(prompt);
      } else {
        return {
          success: false,
          error: 'Invalid AI service configuration. Supported models: "gemini" or "deepseek".'
        };
      }
    } catch (error) {
      console.error('AI Service Error:', error);
      return {
        success: false,
        error: 'Failed to generate resume. Please try again later.'
      };
    }
  }

  private static async callGemini(prompt: string): Promise<AIServiceResponse> {
    const apiKey = process.env.GOOGLE_API_KEY;
    
    if (!apiKey) {
      return {
        success: false,
        error: 'Google API key not configured. Please set GOOGLE_API_KEY environment variable.'
      };
    }

    const response = await fetch(this.GEMINI_URL, {
      method: 'POST',
      headers: {
        'x-goog-api-key': apiKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 8192,
        }
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      return {
        success: false,
        error: `Gemini API error: ${response.status} ${response.statusText} - ${errorData.error?.message || 'Unknown error'}`
      };
    }

    const data = await response.json();
    const content = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!content) {
      return {
        success: false,
        error: 'No content generated by Gemini API'
      };
    }

    return {
      success: true,
      content: content.trim(),
      model: 'Google Gemini 2.5 Flash'
    };
  }

  private static async callDeepSeek(prompt: string): Promise<AIServiceResponse> {
    const apiKey = process.env.OPENROUTER_API_KEY;
    
    if (!apiKey) {
      return {
        success: false,
        error: 'OpenRouter API key not configured. Please set OPENROUTER_API_KEY environment variable.'
      };
    }

    const response = await fetch(this.OPENROUTER_URL, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': 'https://ai-resume-master.vercel.app',
        'X-Title': 'AI Resume Master'
      },
      body: JSON.stringify({
        model: 'deepseek/deepseek-chat-v3.1:free',
        messages: [
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 8192,
        top_p: 0.95,
        frequency_penalty: 0.5,
        stream: false
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      return {
        success: false,
        error: `OpenRouter API error: ${response.status} ${response.statusText} - ${errorData.error?.message || 'Unknown error'}`
      };
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content;

    if (!content) {
      return {
        success: false,
        error: 'No content generated by DeepSeek V3.1 API'
      };
    }

    return {
      success: true,
      content: content.trim(),
      model: 'DeepSeek V3.1 (via OpenRouter)'
    };
  }
} 